// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zvykziimtlrxuezhkvni.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp2eWt6aWltdGxyeHVlemhrdm5pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MDY4ODgsImV4cCI6MjA3MTI4Mjg4OH0.D7KFVztKlsFDxbIGgK0O1_ZpK0BsNlWaYpzTW4pCugs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});