// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jzwahqqzbdbgpzuoguqy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp6d2FocXF6YmRiZ3B6dW9ndXF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4NTEyMzAsImV4cCI6MjA3MDQyNzIzMH0.1ozzVPYVvVQuajm-TzWOP46ZEFXOZ9uhi7UyY8XU0yE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});